use client's transport, if it is set
go-pkgz/requester pull request #3
Opened 2021-08-05 13:38 UTC by Semior001

2021-08-05 17:18 UTC, umputun requested changes
thx, looking good. A few minor things regarding the test

2021-08-05 17:18 UTC, umputun commented on requester_test.go
> +	t.Cleanup(ts.Close)
not sure what the point of doing Cleanup call here instead of the direct defer ts.Close like in all other tests

2021-08-05 17:18 UTC, umputun commented on requester_test.go
> +	assert.True(t, caughtReq)
I think, this direct access to caughtReq may cause some linters to complain and my evne fail with -race flag in some cases as it set in ts hadnler's goroutine and read directly wihout any sync. I's suggest wrap it with atomic

2021-08-05 17:18 UTC, umputun commented on requester_test.go
> +		t.FailNow()
maybe replace with t.Fatal("remote should not be reached due to redirect") ?

2021-08-05 17:18 UTC, umputun commented on requester_test.go
smilar test missed for Clent test. Probably can be added directly to this one

2021-08-05 20:03 UTC, umputun reviewed
lgtm

could you pls rebase to a single commit and I'll merge it in

2021-08-06 13:07 UTC, umputun approved these changes

2021-08-10 09:51 UTC, Semior001 commented
any updates here? coveralls reported that there is a decrease in coverage, but this decrease is caused by reducing amount of lines in the `requester.go`

2021-08-22 18:47 UTC, merged